model_version: 2.0
product_va_config:
  name: Document Database Benchmark
  product_name: CNIV
  version:
  va_template_version: 2.0.0
  description: Document Database Benchmark vulnerability analysis report