{{ if index .Values "eric-data-document-database-pg" "enabled" }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "eric-enm-document-database-benchmark.name" . }}-ddbpg-secret
  labels:
    {{- include "eric-enm-document-database-benchmark.common.labels" . | nindent 4 }}
  annotations:
  {{- include "eric-enm-document-database-benchmark.product.annotations" . | nindent 4}}
type: Opaque
data:
  # For custom user
  {{- if .Values.postgresCredentials.customUser }}
  custom-user: {{ .Values.postgresCredentials.customUser | b64enc | quote }}
  {{- else }}
  custom-user: {{ "custom-postgres" | b64enc | quote }}
  {{- end }}

  # For custom user password
  {{- if .Values.postgresCredentials.customPwd }}
  custom-pwd: {{ .Values.postgresCredentials.customPwd | b64enc | quote }}
  {{- else }}
  custom-pwd: {{ randAlphaNum 10 | b64enc | quote }}
  {{- end }}

  # For super user and password
  super-user: {{ "postgres" | b64enc | quote }}
  {{- if .Values.postgresCredentials.superPwd }}
  super-pwd: {{ .Values.postgresCredentials.superPwd | b64enc | quote }}
  {{- else }}
  super-pwd: {{ "VGVzdFBhc3N3MHJk" | quote }}
  {{- end }}

  # For metrics user and password
  metrics-user: {{ "exporter" | b64enc | quote }}
  metrics-pwd: {{ "ZXhwb3J0ZXI=" | quote }}

  # For replication user and password
  replica-user: {{ "replica" | b64enc | quote }}
  replica-pwd: {{ "cmVwbGljYQ==" | quote }}
{{ end }}

