apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "eric-enm-document-database-benchmark.name" . }}-pg-bench-config
  labels:
    {{- include "eric-enm-document-database-benchmark.common.labels" . | nindent 4 }}
  annotations:
  {{- include "eric-enm-document-database-benchmark.product.annotations" . | nindent 4}}
data:
  description: "pgbench parameters configmap"
  config.yaml: |-
{{- include "eric-enm-document-database-benchmark.pgbench.configs" . | nindent 4  -}}