---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "eric-enm-document-database-benchmark.name" . }}-sa
  labels:
    {{- include "eric-enm-document-database-benchmark.common.labels" . | nindent 4 }}
  annotations:
  {{- include "eric-enm-document-database-benchmark.product.annotations" . | nindent 4}}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: {{ include "eric-enm-document-database-benchmark.name" . }}-job-reader
  labels:
    {{- include "eric-enm-document-database-benchmark.common.labels" . | nindent 4 }}
  annotations:
  {{- include "eric-enm-document-database-benchmark.product.annotations" . | nindent 4}}
rules:
  - apiGroups: ["batch"]
    resources: ["jobs"]
    verbs: ["get","watch","list"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ include "eric-enm-document-database-benchmark.name" . }}-role-binding
  labels:
    {{- include "eric-enm-document-database-benchmark.common.labels" . | nindent 4 }}
  annotations:
  {{- include "eric-enm-document-database-benchmark.product.annotations" . | nindent 4}}
subjects:
    - kind: ServiceAccount
      name: {{ include "eric-enm-document-database-benchmark.name" . }}-sa
roleRef:
  kind: Role
  name: {{ include "eric-enm-document-database-benchmark.name" . }}-job-reader
  apiGroup: rbac.authorization.k8s.io