apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "eric-enm-document-database-benchmark.name" . }}-threshold-config
  labels:
    {{- include "eric-enm-document-database-benchmark.common.labels" . | nindent 4 }}
  annotations:
  {{- include "eric-enm-document-database-benchmark.product.annotations" . | nindent 4}}
data:
  description: "Thresholds"
  config.yaml: |
    requirements:
      tx_per_second:
        description: "Transactions per second, including the time it takes to establish the connection."
        expectedResult:
          minimum: {{ .Values.requirements.tx_per_second.requirements.expectedResult.minimum }}
